name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 using SSH Action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
          
            cd /home/ec2-user/git/Dummy

            # Pull latest code
            git pull origin main

            # Build Docker image
            sudo docker build -t dummy-admin .

            # Stop and remove old container
            sudo docker rm -f dummy-admin || true

            # Run new container
            sudo docker run -d  --name dummy-admin -p 8080:8080 dummy-admin
